apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.service.port | quote }}
  PG_HOST: {{ .Values.postgres.host | quote }}
  PG_PORT: {{ .Values.postgres.port | quote }}
  PG_DB: {{ .Values.postgres.database | quote }}
  PG_USER: {{ .Values.postgres.username | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafkaService.kafkaBootstrapServers | quote }}
  NOTIFICATIONS_TOPIC: {{ .Values.kafkaService.notificationsTopic | quote }}
  NOTIFICATIONS_GROUP: {{ .Values.kafkaService.consumerGroup | quote }}