apiVersion: v1
kind: Secret
metadata:
  name: notifications
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
type: Opaque
stringData:
  PG_PASSWORD: {{ .Values.postgres.dbPassword | quote }}