apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.service.port | quote }}
  ACCOUNTS_BASE_URL: {{ .Values.urls.accountsUrl | quote }}
  CASH_BASE_URL: {{ .Values.urls.cashUrl | quote }}
  TRANSFER_BASE_URL: {{ .Values.urls.transferUrl | quote }}
  NOTIFICATIONS_BASE_URL: {{ .Values.urls.notificationsUrl | quote }}
  BANK_JWK_SET_URI: {{ .Values.urls.jwkSetUrl | quote }}
  ZIPKIN_ENDPOINT: {{ .Values.management.zipkin.endpoint | quote }}
  LOGSTASH_HOST: {{ .Values.logstash.host | quote }}
  LOGSTASH_PORT: {{ .Values.logstash.port | quote }}