services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    restart: unless-stopped
    command: ["start-dev", "--import-realm", "--http-port=9090"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "9090:9090"
    volumes:
      - ./keycloak/my-bank-realm.json:/opt/keycloak/data/import/my-bank-realm.json:ro

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    environment:
      SERVER_PORT: 8081
      BANK_JWK_SET_URI: http://keycloak:9090/realms/my-bank/protocol/openid-connect/certs
      NOTIFICATIONS_BASE_URL: http://notifications:8082
      ACCOUNTS_BASE_URL: http://accounts:8083
      CASH_BASE_URL: http://cash:8090
      TRANSFER_BASE_URL: http://transfer:8084
    depends_on:
      accounts-service: { condition: service_started }
      cash-service: { condition: service_started }
      transfer-service: { condition: service_started }
    ports:
      - "8081:8081"


  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - bank-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank -d bank"]
      interval: 5s
      timeout: 3s
      retries: 10


  front-ui:
    build:
      context: .
      dockerfile: front-ui/Dockerfile
    container_name: my-bank-front
    restart: unless-stopped
    environment:
      SERVER_PORT: 8080
      BANK_GATEWAY_URL: http://gateway:8081
      BANK_AUTHORIZATION_URI: http://localhost:9090/realms/my-bank/protocol/openid-connect/auth
      BANK_TOKEN_URI: http://keycloak:9090/realms/my-bank/protocol/openid-connect/token
      BANK_USER_INFO_URI: http://keycloak:9090/realms/my-bank/protocol/openid-connect/userinfo
      BANK_JWK_SET_URI: http://keycloak:9090/realms/my-bank/protocol/openid-connect/certs
      BANK_LOGOUT_URI: http://localhost:9090/realms/my-bank/protocol/openid-connect/logout
      FRONT_CLIENT_ID: front-ui
      FRONT_CLIENT_SECRET: front-secret
    ports:
      - "8080:8080"
    depends_on:
      - gateway
      - keycloak

  accounts-service:
    build:
      context: .
      dockerfile: accounts-service/Dockerfile
    container_name: my-bank-accounts
    restart: unless-stopped
    environment:
      SERVER_PORT: 8083
      PG_HOST: postgres
      BANK_JWK_SET_URI: http://keycloak:9090/realms/my-bank/protocol/openid-connect/certs
      BANK_TOKEN_URI: http://keycloak:9090/realms/my-bank/protocol/openid-connect/token
      BANK_ISSUER_URI: http://localhost:9090/realms/my-bank
      ACCOUNTS_DB_URL: jdbc:postgresql://postgres:5432/bank
      ACCOUNTS_DB_USER: bank
      ACCOUNTS_DB_PASSWORD: bank
      ACCOUNTS_CLIENT_ID: accounts-service
      ACCOUNTS_CLIENT_SECRET: accounts-secret
      NOTIFICATIONS_BASE_URL: http://notifications:8082
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started


  cash-service:
    build:
      context: .
      dockerfile: cash-service/Dockerfile
    container_name: my-bank-cash
    restart: unless-stopped
    environment:
      SERVER_PORT: 8090
      PG_HOST: postgres
      BANK_JWK_SET_URI: http://keycloak:9090/realms/my-bank/protocol/openid-connect/certs
      BANK_TOKEN_URI: http://keycloak:9090/realms/my-bank/protocol/openid-connect/token
      BANK_ISSUER_URI: http://localhost:9090/realms/my-bank
      CASH_CLIENT_ID: cash-service
      CASH_CLIENT_SECRET: cash-secret
      NOTIFICATIONS_BASE_URL: http://notifications:8082
      ACCOUNTS_BASE_URL: http://accounts:8083
    depends_on:
      - accounts-service
      - notifications-service
      - keycloak

  transfer-service:
    build:
      context: .
      dockerfile: transfer-service/Dockerfile
    container_name: my-bank-transfer
    restart: unless-stopped
    environment:
      SERVER_PORT: 8084
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: bank
      PG_USER: bank
      PG_PASSWORD: bank
      BANK_JWK_SET_URI: http://keycloak:9090/realms/my-bank/protocol/openid-connect/certs
      BANK_TOKEN_URI: http://keycloak:9090/realms/my-bank/protocol/openid-connect/token
      BANK_ISSUER_URI: http://localhost:9090/realms/my-bank
      TRANSFER_CLIENT_ID: transfer-service
      TRANSFER_CLIENT_SECRET: transfer-secret
      NOTIFICATIONS_BASE_URL: http://notifications:8082
      ACCOUNTS_BASE_URL: http://accounts:8083
    depends_on:
      - accounts-service
      - notifications-service
      - keycloak

  notifications-service:
    build:
      context: .
      dockerfile: notifications-service/Dockerfile
    container_name: my-bank-notifications
    restart: unless-stopped
    environment:
      SERVER_PORT: 8082
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: bank
      PG_USER: bank
      PG_PASSWORD: bank
      BANK_JWK_SET_URI: http://keycloak:9090/realms/my-bank/protocol/openid-connect/certs
      BANK_ISSUER_URI: http://localhost:9090/realms/my-bank
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started


volumes:
  bank-postgres-data: