spring:
  application:
    name: cash

  security:
    oauth2:
      client:
        registration:
          accounts-service:
            client-id: ${CASH_CLIENT_ID:cash-service}
            client-secret: ${CASH_CLIENT_SECRET:cash-secret}
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            token-uri: ${BANK_TOKEN_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/token}
            jwk-set-uri: ${BANK_JWK_SET_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/certs}
      resourceserver:
        jwt:
          issuer-uri: ${BANK_ISSUER_URI:http://localhost:9090/realms/my-bank}
          jwk-set-uri: ${BANK_JWK_SET_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/certs}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 15000
        request.timeout.ms: 5000
server:
  port: ${SERVER_PORT:8090}

bank:
  accounts-base-url: ${ACCOUNTS_BASE_URL:http://localhost:8083}
  notifications-topic: ${NOTIFICATIONS_TOPIC:notifications-service}

resilience4j:
  circuitbreaker:
    instances:
      accounts:
        sliding-window-type: count_based
        sliding-window-size: 8
        minimum-number-of-calls: 4
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 2

logging:
  level:
    org.springframework.security: INFO
    io.github.resilience4j: INFO