apiVersion: v1
kind: Secret
metadata:
  name: cash
  labels:
    {{- include "cash.labels" . | nindent 4 }}
type: Opaque
stringData:
  CASH_CLIENT_SECRET: {{ .Values.authentification.clientSecret | quote }}