replicaCount: 1

image:
  repository: openzipkin/zipkin
  tag: "3.5.1"
  pullPolicy: IfNotPresent

service:
  port: 9411

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi