spring:
  application:
    name: gateway
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}-${random.value}
        prefer-ip-address: true
    gateway:
      routes:
        - id: accounts-service
          uri: lb://accounts
          predicates:
            - Path=/api/accounts/**
          filters:
            - name: CircuitBreaker
              args:
                name: accounts
        - id: cash-service
          uri: lb://cash
          predicates:
            - Path=/api/cash/**
          filters:
            - name: CircuitBreaker
              args:
                name: cash
        - id: transfer-service
          uri: lb://transfer
          predicates:
            - Path=/api/transfers/**
          filters:
            - name: CircuitBreaker
              args:
                name: transfer
        - id: notifications-service
          uri: lb://notifications
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: CircuitBreaker
              args:
                name: notifications

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${BANK_JWK_SET_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/certs}
server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    org.springframework.cloud.gateway: INFO