spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Authorization
      routes:
        - id: accounts-service
          uri: ${ACCOUNTS_BASE_URL:http://localhost:8083}
          predicates:
            - Path=/api/accounts/**
          filters:
            - name: CircuitBreaker
              args:
                name: accounts
        - id: cash-service
          uri: ${CASH_BASE_URL:http://localhost:8090}
          predicates:
            - Path=/api/cash/**
          filters:
            - name: CircuitBreaker
              args:
                name: cash
        - id: transfer-service
          uri: ${TRANSFER_BASE_URL:http://localhost:8084}
          predicates:
            - Path=/api/transfers/**
          filters:
            - name: CircuitBreaker
              args:
                name: transfer

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${BANK_JWK_SET_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/certs}
server:
  port: ${SERVER_PORT:8081}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
    org.springframework.security.authorization: INFO
    org.springframework.security.access: INFO
logstash:
  host: ${LOGSTASH_HOST:localhost}
  port: ${LOGSTASH_PORT:5000}