apiVersion: v1
kind: Secret
metadata:
  name: accounts
  labels:
    {{- include "accounts.labels" . | nindent 4 }}
type: Opaque
stringData:
  ACCOUNTS_DB_PASSWORD: {{ .Values.postgres.dbPassword | quote }}
  ACCOUNTS_CLIENT_SECRET: {{ .Values.authentification.clientSecret | quote }}