apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash
  labels:
    app.kubernetes.io/name: logstash
    app.kubernetes.io/component: logging
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.enabled: false
  logstash.conf: |
    input {
      tcp {
        port => {{ .Values.service.logsPort }}
        codec => json_lines
      }
    }

    filter {
      if [timestamp] {
        date {
          match => ["timestamp", "ISO8601"]
          target => "@timestamp"
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["{{ .Values.elasticsearch.url }}"]
        index => "my-bank-logs-%{+YYYY.MM.dd}"
      }
    }