apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app.kubernetes.io/name: logstash
    app.kubernetes.io/component: logging
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: logstash
  ports:
    - name: logs
      port: {{ .Values.service.logsPort }}
      targetPort: logs
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: logs