apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provider
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: dashboards
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: bank-app
        type: file
        disableDeletion: true
        editable: false
        options:
          path: /var/lib/grafana/dashboards