server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: front-ui
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: ${BANK_AUTHORIZATION_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/auth}
            token-uri: ${BANK_TOKEN_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/token}
            user-info-uri: ${BANK_USER_INFO_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/userinfo}
            jwk-set-uri: ${BANK_JWK_SET_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/certs}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: ${FRONT_CLIENT_ID:front-ui}
            client-secret: ${FRONT_CLIENT_SECRET:front-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email

bank:
  gateway-url: ${BANK_GATEWAY_URL:http://localhost:8081}
  logout-url: ${BANK_LOGOUT_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/logout}

management:
  endpoints:
    web:
      exposure:
        include: health,info