spring:
  application:
    name: transfer
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB:bank}
    username: ${PG_USER:bank}
    password: ${PG_PASSWORD:bank}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: transfer
        format_sql: false
  flyway:
    enabled: true
    schemas: transfer
    default-schema: transfer
    create-schemas: true

  security:
    oauth2:
      client:
        registration:
          accounts-service:
            client-id: ${TRANSFER_CLIENT_ID:transfer-service}
            client-secret: ${TRANSFER_CLIENT_SECRET:transfer-secret}
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            token-uri: ${BANK_TOKEN_URI:http://localhost:8090/realms/my-bank/protocol/openid-connect/token}
            jwk-set-uri: ${BANK_JWK_SET_URI:http://localhost:8090/realms/my-bank/protocol/openid-connect/certs}
      resourceserver:
        jwt:
          issuer-uri: ${BANK_ISSUER_URI:http://localhost:8090/realms/my-bank}
          jwk-set-uri: ${BANK_JWK_SET_URI:http://localhost:8090/realms/my-bank/protocol/openid-connect/certs}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 15000
        request.timeout.ms: 5000
server:
  port: ${SERVER_PORT:8084}

bank:
  accounts-base-url: ${ACCOUNTS_BASE_URL:http://localhost:8083}
  notifications-topic: ${NOTIFICATIONS_TOPIC:notifications-service}
resilience4j:
  circuitbreaker:
    instances:
      accounts:
        sliding-window-type: count_based
        sliding-window-size: 8
        minimum-number-of-calls: 4
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 2
transfer:
  outbox:
    max-retry: 10
    polling-interval-ms: 5000
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
logging:
  level:
    org.springframework.security: INFO
    io.github.resilience4j: INFO
logstash:
  host: ${LOGSTASH_HOST:localhost}
  port: ${LOGSTASH_PORT:5000}