spring:
  application:
    name: transfer
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}-${random.value}
        prefer-ip-address: true
      config:
        enabled: true
        format: yaml
        prefix: config
        default-context: ${spring.application.name}
        fail-fast: false

  security:
    oauth2:
      client:
        registration:
          accounts-service:
            client-id: ${TRANSFER_CLIENT_ID:transfer-service}
            client-secret: ${TRANSFER_CLIENT_SECRET:transfer-secret}
            authorization-grant-type: client_credentials
            provider: keycloak
          notifications-service:
            client-id: ${TRANSFER_CLIENT_ID:transfer-service}
            client-secret: ${TRANSFER_CLIENT_SECRET:transfer-secret}
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            token-uri: ${BANK_TOKEN_URI:http://localhost:8090/realms/my-bank/protocol/openid-connect/token}
            jwk-set-uri: ${BANK_JWK_SET_URI:http://localhost:8090/realms/my-bank/protocol/openid-connect/certs}
      resourceserver:
        jwt:
          issuer-uri: ${BANK_ISSUER_URI:http://localhost:8090/realms/my-bank}
          jwk-set-uri: ${BANK_JWK_SET_URI:http://localhost:8090/realms/my-bank/protocol/openid-connect/certs}

server:
  port: ${SERVER_PORT:8084}

bank:
  accounts-base-url: ${ACCOUNTS_BASE_URL:http://localhost:8083}
  notifications-base-url: ${NOTIFICATIONS_BASE_URL:http://localhost:8082}

resilience4j:
  circuitbreaker:
    instances:
      accounts:
        sliding-window-type: count_based
        sliding-window-size: 8
        minimum-number-of-calls: 4
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 2
      notifications:
        sliding-window-type: count_based
        sliding-window-size: 8
        minimum-number-of-calls: 4
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 2

logging:
  level:
    org.springframework.security: INFO
    io.github.resilience4j: INFO