apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.config.adminUsername | quote }}
  KC_HEALTH_ENABLED: {{ .Values.config.healthEnabled | quote }}
  KC_HTTP_ENABLED: {{ .Values.config.httpEnabled | quote }}
  KC_HOSTNAME_STRICT: {{ .Values.config.hostnameStrict | quote }}
  KC_HOSTNAME: {{ .Values.config.hostname | quote }}