replicaCount: 1

image:
  repository: accounts
  registry: ""
  pullPolicy: IfNotPresent
  tag: "0.0.1"

service:
  port: 8083

postgres:
  url: "jdbc:postgresql://postgres:5432/bank"
  dbPassword: bank
  database: bank
  username: bank
  host: postgres
  port: 5432
  secretName: postgres

authentification:
  clientId: accounts-service
  clientSecret: accounts-secret
  jwkSetUri: "http://keycloak:9090/realms/my-bank/protocol/openid-connect/certs"
  tokenUri: "http://keycloak:9090/realms/my-bank/protocol/openid-connect/token"

urls:
  kafkaBootstrapServers: "kafka:9092"
  notificationsTopic: "notifications-service"

probes:
  readiness:
    path: "/actuator/health"
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    path: "/actuator/health"
    initialDelaySeconds: 40
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 768Mi
management:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

logstash:
  host: logstash
  port: 5000