apiVersion: v1
kind: ConfigMap
metadata:
  name: transfer
  labels:
    {{- include "transfer.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.service.port | quote }}
  PG_HOST: {{ .Values.postgres.host | quote }}
  PG_PORT: {{ .Values.postgres.port | quote }}
  PG_DB: {{ .Values.postgres.database | quote }}
  PG_USER: {{ .Values.postgres.username | quote }}
  ACCOUNTS_BASE_URL: {{ .Values.urls.accountsUrl | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.urls.kafkaBootstrapServers | quote }}
  NOTIFICATIONS_TOPIC: {{ .Values.urls.notificationsTopic | quote }}
  BANK_JWK_SET_URI: {{ .Values.authentification.jwkSetUri | quote }}
  BANK_TOKEN_URI: {{ .Values.authentification.tokenUri | quote }}
  TRANSFER_CLIENT_ID: {{ .Values.authentification.clientId | quote }}