apiVersion: v1
kind: Secret
metadata:
  name: transfer
  labels:
    {{- include "transfer.labels" . | nindent 4 }}
type: Opaque
stringData:
  TRANSFER_CLIENT_SECRET: {{ .Values.authentification.clientSecret | quote }}
  PG_PASSWORD: {{ .Values.postgres.dbPassword | quote }}