server:
  port: ${SERVER_PORT:8082}
spring:
  application:
    name: notifications
  config:
    import: "optional:consul:"

  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB:bank}
    username: ${PG_USER:bank}
    password: ${PG_PASSWORD:bank}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: notifications
        format_sql: false
  flyway:
    enabled: true
    schemas: notifications
    default-schema: notifications
    create-schemas: true
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}-${random.value}
        prefer-ip-address: true
      config:
        enabled: true
        format: yaml
        prefix: config
        default-context: ${spring.application.name}
        fail-fast: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${BANK_ISSUER_URI:http://localhost:9090/realms/my-bank}
          jwk-set-uri: ${BANK_JWK_SET_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/certs}

  resilience4j:
    circuitbreaker:
      instances:
        notifications:
          sliding-window-size: 5
          failure-rate-threshold: 50