spring:
  application:
    name: accounts
  security:
    oauth2:
      client:
        registration:
          notifications-service:
            client-id: ${ACCOUNTS_CLIENT_ID:accounts-service}
            client-secret: ${ACCOUNTS_CLIENT_SECRET:accounts-secret}
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            token-uri: ${BANK_TOKEN_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/token}
            jwk-set-uri: ${BANK_JWK_SET_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/certs}
      resourceserver:
        jwt:
          issuer-uri: ${BANK_ISSUER_URI:http://localhost:9090/realms/my-bank}
          jwk-set-uri: ${BANK_JWK_SET_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/certs}

  datasource:
    url: ${ACCOUNTS_DB_URL:jdbc:postgresql://localhost:5432/bank}
    username: ${ACCOUNTS_DB_USER:bank}
    password: ${ACCOUNTS_DB_PASSWORD:bank}
  flyway:
    schemas: accounts
    default-schema: accounts
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: accounts
server:
  port: ${SERVER_PORT:8083}
bank:
  notifications-base-url: ${NOTIFICATIONS_BASE_URL:http://localhost:8082}