spring:
  application:
    name: accounts
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${BANK_TOKEN_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/token}
            jwk-set-uri: ${BANK_JWK_SET_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/certs}
      resourceserver:
        jwt:
          issuer-uri: ${BANK_ISSUER_URI:http://localhost:9090/realms/my-bank}
          jwk-set-uri: ${BANK_JWK_SET_URI:http://localhost:9090/realms/my-bank/protocol/openid-connect/certs}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 15000
        request.timeout.ms: 5000
  datasource:
    url: ${ACCOUNTS_DB_URL:jdbc:postgresql://localhost:5432/bank}
    username: ${ACCOUNTS_DB_USER:bank}
    password: ${ACCOUNTS_DB_PASSWORD:bank}
  flyway:
    schemas: accounts
    default-schema: accounts
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: accounts
server:
  port: ${SERVER_PORT:8083}
bank:
  notifications-topic: ${NOTIFICATIONS_TOPIC:notifications-service}