apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/component: logging
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kibana
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http