replicaCount: 1

image:
  repository: transfer
  registry: ""
  pullPolicy: IfNotPresent
  tag: "0.0.1"

service:
  port: 8084

postgres:
  dbPassword: bank
  database: bank
  username: bank
  host: postgres
  port: 5432
  secretName: postgres

authentification:
  clientId: transfer-service
  clientSecret: transfer-secret
  jwkSetUri: "http://keycloak:9090/realms/my-bank/protocol/openid-connect/certs"
  tokenUri: "http://keycloak:9090/realms/my-bank/protocol/openid-connect/token"

urls:
  notificationsUrl: "http://notifications:8082"
  accountsUrl: "http://accounts:8083"

probes:
  readiness:
    path: "/actuator/health"
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    path: "/actuator/health"
    initialDelaySeconds: 40
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 768Mi