replicaCount: 1

image:
  repository: notifications
  registry: ""
  pullPolicy: IfNotPresent
  tag: "0.0.1"

service:
  port: 8082

postgres:
  dbPassword: bank
  database: bank
  username: bank
  host: postgres
  port: 5432
  secretName: postgres


probes:
  readiness:
    path: "/actuator/health"
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    path: "/actuator/health"
    initialDelaySeconds: 40
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3

kafkaService:
  kafkaBootstrapServers: "kafka:9092"
  notificationsTopic: "notifications-service"
  consumerGroup: "notifications-service"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 768Mi

management:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
logstash:
  host: logstash
  port: 5000