replicaCount: 1

image:
  repository: elasticsearch
  tag: "8.18.2"
  pullPolicy: IfNotPresent

service:
  port: 9200

javaOpts: "-Xms512m -Xmx512m"

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 4Gi