apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.name" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}