image:
  repository: apache/kafka
  tag: "3.9.0"
  pullPolicy: IfNotPresent

service:
  port: 9092

clusterId: bank-kafka-cluster-01

topic:
  name: notifications-service
  partitions: 1
  replicationFactor: 1

urls:
  kafkaBootstrapServers: "kafka:9092"
  notificationsTopic: "notifications-service"

persistence:
  enabled: true
  size: 1Gi
  storageClassName: ""

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"